package dev.boooiil.historia.core.classes.enums.proficiency;

public enum SkillType {
    NAME_TAG,
    FEATHER_FALL,
    QUICK_CHARGE,
    EFFICIENCY_PICKAXE,
    EFFICIENCY_SHOVEL,
    EFFICIENCY_AXE,
    CHANCE_EXTRA_ORE,
    CHANCE_EXTRA_WOOD,
    CHANCE_EXTRA_FEATHERS,
    CHANCE_NO_ANVIL_DAMAGE,
    CHANCE_NO_CONSUME_BLOCK,
    LADDER_BYPASS,
    IGNITE_OIL,
    BREAK_GRASS,
    TAME_ANIMALS,
    SWEEPING_EDGE,
    BREAK_BEEHIVE,
    APPLY_UNBREAKING,
    APPLY_SHARPNESS,
    SHEAR_CHICKEN,
    HARVEST_BONES,
    HARVEST_LEATHER,
    MAKE_KNOWLEDGE_BOOK
}