
foods:
    not-listed: 6
    list:
        - BEEF: 4
        - COOKED_BEEF: 7
        - RABBIT_STEW: 5
        - BREAD: 7
        - APPLE: 12
        - COD: 3
        - SALMON: 3
        - TROPICAL_FISH: 3
        - COOKED_COD: 5
        - COOKED_SALMON: 5
        - MUSHROOM_STEW: 5
        - MELON_SLICE: 
        - CHICKEN: 3
        - COOKED_CHICKEN: 5
        - CARROT: 25
        - POTATO: 40
        - BAKED_POTATO: 5
        - PUMPKIN_PIE: 3
        - RABBIT: 3
        - COOKED_RABBIT: 5
        - MUTTON: 3
        - COOKED_MUTTON: 3
        - BEETROOT: 14
        - BEETROOT_SOUP: 3
        - SWEET_BERRIES: 12
        - COOKIE: 16
    effects:
        - POISON: 1
        - CONFUSION: 1

classes:
    list: [Warrior, Archer, Fisherman, Miner, Blacksmith, Hunter, Apothecary, Architect, Lumberjack, Farmer]
    Warrior:
        stats:
            health: 26
            baseFood: 16
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.10
            sweepingEdge: true
    Archer:
        stats:
            health: 18
            baseFood: 26
            exhaustion: 0
            saturation: 0
            speed: 0.3
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            quickCharge: true
            igniteOil: true
    Fisherman:
        stats:
            health: 18
            baseFood: 30
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            extractBones: true
            extractOil: true
    Miner:
        stats:
            health: 22
            baseFood: 26
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            extraOreChance: true
            efficiencyPickaxe: true
            specialItems: true
    Blacksmith:
        stats:
            health: 24
            baseFood: 26
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            highTierArmor: true
            applyUnbreaking: true
            craftSaddle: true
            chanceAnvilNoDamage: true
    Hunter:
        stats:
            health: 16
            baseFood: 24
            exhaustion: 0
            saturation: 0
            speed: 0.4
        extra:
            nametag: false
            beheadChance: 0.07
            bonesFromAnimals: true
            tameAnimals: true
            extraWool: true
            extraFeathers: true
            craftSaddle: true
    Apothecary:
        stats:
            health: 20
            baseFood: 22
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            extractOil: true
            craftGunpowder: true
            knowledgeBook: true
    Architect:
        stats:
            health: 20
            baseFood: 28
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            chanceNoConsumeBlock: true
            featherfall: true
            incomeMultiplier: 1.2
    Lumberjack:
        stats:
            health: 26
            baseFood: 18
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.08
            chanceExtraWood: true
            efficiencyAxe: true
    Farmer:
        stats:
            health: 20
            baseFood: 20
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.6
            beheadChance: 0.10
            doubleHarvestChance: 0.05
            breakBeehive: true
            breakGrass: true
            instantGrowChance: 0.3

weapons:

    list: [Placeholder_Sword]
    Placeholder_Sword:
        - damage: 10.0

armor:
    
    list: ["Placeholder_Helmet", "Placeholder_Chestplate", "Placeholder_Leggings", "Placeholder_Boots"]
    Placeholder_Helmet: 
        - armor: 10.0
    Placeholder_Chestplate: 
        - armor: 10.0
    Placeholder_Leggings: 
        - armor: 10.0
    Placeholder_Boots: 
        - armor: 10.0