
foods:
    not-listed: 6
    list:
        - BEEF: 4
        - COOKED_BEEF: 7
        - RABBIT_STEW: 5
        - BREAD: 7
        - APPLE: 12
        - COD: 3
        - SALMON: 3
        - TROPICAL_FISH: 3
        - COOKED_COD: 5
        - COOKED_SALMON: 5
        - MUSHROOM_STEW: 5
        - MELON_SLICE: 
        - CHICKEN: 3
        - COOKED_CHICKEN: 5
        - CARROT: 25
        - POTATO: 40
        - BAKED_POTATO: 5
        - PUMPKIN_PIE: 3
        - RABBIT: 3
        - COOKED_RABBIT: 5
        - MUTTON: 3
        - COOKED_MUTTON: 3
        - BEETROOT: 14
        - BEETROOT_SOUP: 3
        - SWEET_BERRIES: 12
        - COOKIE: 16
    effects:
        - POISON: 1
        - CONFUSION: 1

MySQL:
    user: User
    password: Titaniumsilky26
    database: world
    ip: "192.168.0.12"
    port: 3306

classes:
    list: ["Warrior", "Archer", "Fisherman", "Miner", "Blacksmith", "Hunter", "Apothecary", "Architect", "Lumberjack", "Farmer"]
    Warrior:
        stats:
            health: 26
            baseFood: 16
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.10
            sweepingEdge: true
    Archer:
        stats:
            health: 18
            baseFood: 26
            exhaustion: 0
            saturation: 0
            speed: 0.3
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            quickCharge: true
            igniteOil: true
    Fisherman:
        stats:
            health: 18
            baseFood: 30
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            extractBones: true
            extractOil: true
    Miner:
        stats:
            health: 22
            baseFood: 26
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            extraOreChance: true
            efficiencyPickaxe: true
            specialItems: true
    Blacksmith:
        stats:
            health: 24
            baseFood: 26
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            highTierArmor: true
            applyUnbreaking: true
            craftSaddle: true
            chanceAnvilNoDamage: true
    Hunter:
        stats:
            health: 16
            baseFood: 24
            exhaustion: 0
            saturation: 0
            speed: 0.4
        extra:
            nametag: false
            beheadChance: 0.07
            bonesFromAnimals: true
            tameAnimals: true
            extraWool: true
            extraFeathers: true
            craftSaddle: true
    Apothecary:
        stats:
            health: 20
            baseFood: 22
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            extractOil: true
            craftGunpowder: true
            knowledgeBook: true
    Architect:
        stats:
            health: 20
            baseFood: 28
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.05
            chanceNoConsumeBlock: true
            featherfall: true
            incomeMultiplier: 1.2
    Lumberjack:
        stats:
            health: 26
            baseFood: 18
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.2
            beheadChance: 0.08
            chanceExtraWood: true
            efficiencyAxe: true
    Farmer:
        stats:
            health: 20
            baseFood: 20
            exhaustion: 0
            saturation: 0
            speed: 0.2
        extra:
            nametag: true
            harvestChance: 0.6
            beheadChance: 0.10
            doubleHarvestChance: 0.05
            breakBeehive: true
            breakGrass: true
            instantGrowChance: 0.3

weapons:

    list: ["Placeholder_Sword"]
    Placeholder_Sword:
        damage: 10.0

armor:
    
    list: [ "Placeholder_Helmet", "Placeholder_Chestplate", "Placeholder_Leggings", "Placeholder_Boots" ]

    Placeholder_Helmet:
    
        item:
            ==: org.bukkit.inventory.ItemStack
            type: IRON_HELMET
            amount: 1
            meta:
                ==: ItemMeta
                meta-type: UNSPECIFIC
                display-name: Placeholder Helmet
                loc-name: Placeholder_Helmet
                lore: [ This is the placeholder helmet. ]

        attributes:
            GENERIC_ARMOR: 10

        crafting: [ IRON_INGOT, IRON_INGOT, IRON_INGOT, IRON_INGOT, AIR, IRON_INGOT, AIR, AIR, AIR ]
    Placeholder_Chestplate: 
        armor: 10.0
    Placeholder_Leggings: 
        armor: 10.0
    Placeholder_Boots: 
        armor: 10.0

items:
    ores:
        list: [ LOW_IRON, MEDIUM_IRON, HIGH_IRON, LOW_BRONZE, MEDIUM_BRONZE, HIGH_BRONZE, LOW_SHEEP_LEATHER, MEDIUM_SHEEP_LEATHER, HIGH_SHEEP_LEATHER ]

        LOW_IRON:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_INGOT
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Low Quality Iron
                    loc-name: LOW_IRON
                    lore: [ This ingot is of a lower quality. ]

            smelt_into: MEDIUM_IRON
            time: 30
            loss: 15
            smelt_times: 1

        MEDIUM_IRON:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_INGOT
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Medium Quality Iron
                    loc-name: MEDIUM_IRON
                    lore: [ This ingot is of a medium quality. ]

            smelt_into: HIGH_IRON
            time: 180
            loss: 10
            smelt_times: 1

        HIGH_IRON:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_INGOT
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: High Quality Iron
                    loc-name: HIGH_IRON
                    lore: [ This ingot is of a high quality. ]

        LOW_BRONZE:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_INGOT
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Low Quality Bronze
                    loc-name: LOW_BRONZE
                    lore: [ This ingot is of a lower quality. ]

            smelt_into: MEDIUM_BRONZE
            time: 30
            loss: 15
            smelt_times: 1

        MEDIUM_BRONZE:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_INGOT
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Medium Quality Bronze
                    loc-name: MEDIUM_BRONZE
                    lore: [ This ingot is of a medium quality. ]

            smelt_into: HIGH_BRONZE
            time: 180
            loss: 10
            smelt_times: 1

        HIGH_BRONZE:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_INGOT
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: High Quality Bronze
                    loc-name: HIGH_BRONZE
                    lore: [ This ingot is of a high quality. ]

        LOW_SHEEP_LEATHER:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: LEATHER
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Low Quality Sheep Leather
                    loc-name: LOW_SHEEP_LEATHER
                    lore: [ This leather is of a lower quality. ]

            smelt_into: MEDIUM_IRON
            time: 30
            loss: 15
            smelt_times: 1

        LOW_COW_LEATHER:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: LEATHER
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Low Quality Cow Leather
                    loc-name: LOW_COW_LEATHER
                    lore: [ This leather is of a lower quality. ]

            smelt_into: MEDIUM_IRON
            time: 30
            loss: 15
            smelt_times: 1

        LOW_PIG_LEATHER:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: LEATHER
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Low Quality Pig Leather
                    loc-name: LOW_PIG_LEATHER
                    lore: [ This leather is of a lower quality. ]

            smelt_into: MEDIUM_IRON
            time: 30
            loss: 15
            smelt_times: 1

        LOW_HORSE_LEATHER:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: LEATHER
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Low Quality Horse Leather
                    loc-name: LOW_HORSE_LEATHER
                    lore: [ This leather is of a lower quality. ]

            smelt_into: MEDIUM_IRON
            time: 30
            loss: 15
            smelt_times: 1

    blocks:
        list: [ LOW_IRON_CHUNK, MEDIUM_IRON_CHUNK, HIGH_IRON_CHUNK, LOW_BRONZE_CHUNK, MEDIUM_BRONZE_CHUNK, HIGH_BRONZE_CHUNK ]

        LOW_IRON_CHUNK:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_ORE
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Low Quality Iron Chunk
                    loc-name: LOW_IRON_CHUNK
                    lore: [ This ore is of a lower quality. ]

        MEDIUM_IRON_CHUNK:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_ORE
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Medium Quality Iron Chunk
                    loc-name: MEDIUM_IRON_CHUNK
                    lore: [ This ore is of a medium quality. ]

        HIGH_IRON_CHUNK:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_ORE
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: High Quality Iron Chunk
                    loc-name: HIGH_IRON_CHUNK
                    lore: [ This ore is of a high quality. ]

        LOW_BRONZE_CHUNK:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_ORE
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Low Quality Bronze Chunk
                    loc-name: LOW_BRONZE_CHUNK
                    lore: [ This ore is of a lower quality. ]

        MEDIUM_BRONZE_CHUNK:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_ORE
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: Medium Quality Bronze Chunk
                    loc-name: MEDIUM_BRONZE_CHUNK
                    lore: [ This ore is of a medium quality. ]

        HIGH_BRONZE_CHUNK:

            item:
                ==: org.bukkit.inventory.ItemStack
                type: IRON_ORE
                amount: 1
                meta:
                    ==: ItemMeta
                    meta-type: UNSPECIFIC
                    display-name: High Quality Bronze Chunk
                    loc-name: HIGH_BRONZE_CHUNK
                    lore: [ This ore is of a high quality. ]


    