main: dev.boooiil.historia.Main
name: Historia
description: Something simple, I guess!
api-version: 1.16
author: boooiil
load: STARTUP
version: 0.6
depend: [WorldGuard, Towny, Vault]

commands:
  ignite:
  item:
  debugitems:
  stats:
  class: