main: dev.boooiil.historia.HistoriaPlugin
name: Historia
description: "Something simple, I guess!"
api: ["1.19", "1.19.2", "1.19.4"]
author: boooiil
load: STARTUP
version: "0.6"
depend: [WorldGuard, Towny, Vault]

commands:
  checkplayers:
    description: Get class information from all users.
    usage: /<command> <player>
    permission: historia.checkplayers
  debug:
    description: Get debug information.
    usage: /<command> [player] <args...>
    permission: historia.debug